### ISSUE TITLE
Incorrect order of condition checks in lines 99 to 1010 in 'src/main.cpp'

### ISSUE THREAD

**Issue by Natsumesosuke** [SET-Scheduling-Project/GEMINI-HPCA2024#3]
In lines 999 to 1010 of the 'main.cpp' file, the condition judgment is in the wrong order.
```cpp
	if (NoC::x_cut * NoC::y_cut == 1) {
		os_ocst_factor = 1;
	}
	else if (os_area >= 30 * 30) {
		os_ocst_factor = 2;
	}
	else if (os_area >= 55 * 55) {
		os_ocst_factor = 4;
	}
	else {
		os_ocst_factor = 1.5;
	}
```
The code first checks whether 'os_area' is greater than or equal to '30 * 30', and then checks whether 'os_area' is greater than or equal to '55 * 55'. This order results in the second judgment never being executed, because any number greater than or equal to '55 * 55' will be greater than or equal to '30 * 30'.

The recommended repair method is to first check whether 'os_area' is greater than or equal to '55 * 55', and then check whether 'os_area' is greater than or equal to '30 * 30'.

Here is the revised code:
```cpp
	if (NoC::x_cut * NoC::y_cut == 1) {
		os_ocst_factor = 1;
	}
	else if (os_area <= 30 * 30) {
		os_ocst_factor = 1.5;
	}
	else if (os_area <= 55 * 55) {
		os_ocst_factor = 2;
	}
	else {
		os_ocst_factor = 4;
	}
```

**Comment by jingweicai** [comment]
thanks! we will revise it!
