### ISSUE TITLE
Can you explain the meaning of the input parameters?

### ISSUE THREAD

**Issue by lovemyyuyu** [SET-Scheduling-Project/GEMINI-HPCA2024#4]
- mm
> 
-  nn
>  
- xx
> 
- yy
> 
- ss
> 
- bb
> 
- rr
> 
-  ff
> 
- xcut
> 
- ycut _serdes_lane
> 
- _DRAM_bw _NoC_bw
> 
-  _mac_num
> 
- _ul3
>

**Comment by jingweicai** [comment]
I have updated their meaning in the main.cpp. please check it, if you have any other questions, welcome to ask us further.
